twig:
    file_name_pattern: '*.twig'

    #pour adapter notre formulaire d'inscription au style bootstrap
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
